import { Store } from "@/types/store";
import { StoreDetails } from "@/types/store-details";

export const mockStores: Store[] = [
  {
    id: 1,
    name: "Matsuri Concept",
    slug: "matsuri-concept",
    image: "/images/stores/matsuri.png",
    deliveryPrice: 0,
    closingTime: "23:00",
    rating: 4.7,
  },
  {
    id: 2,
    name: "Subway - Avenida center",
    slug: "subway-avenida-center",
    image: "/images/stores/subway.png",
    deliveryPrice: 6.0,
    closingTime: "22:30",
    rating: 4.7,
  },
  {
    id: 3,
    name: "Burger King - Colombo",
    slug: "burger-king-colombo",
    image: "/images/stores/burguer-king.png",
    deliveryPrice: 6.0,
    closingTime: "00:00",
    rating: 4.7,
  },
  {
    id: 4,
    name: "McDonald's - Novo Centro",
    slug: "mcdonalds-novo-centro",
    image: "/images/stores/mcdonalds.png",
    deliveryPrice: 0,
    closingTime: "23:30",
    rating: 4.7,
  },
  {
    id: 5,
    name: "Pizza Hut - Centro",
    slug: "pizza-hut-centro",
    image: "/images/stores/pizza-hut.webp",
    deliveryPrice: 8.0,
    closingTime: "01:00",
    rating: 4.5,
  },
  {
    id: 6,
    name: "KFC - Shopping",
    slug: "kfc-shopping",
    image: "/images/stores/kfc.webp",
    deliveryPrice: 5.0,
    closingTime: "22:00",
    rating: 4.6,
  },
  {
    id: 7,
    name: "Outback Steakhouse",
    slug: "outback-steakhouse",
    image: "/images/stores/outback.webp",
    deliveryPrice: 12.0,
    closingTime: "23:45",
    rating: 4.8,
  },
  {
    id: 8,
    name: "Domino's Pizza",
    slug: "dominos-pizza",
    image: "/images/stores/dominos.webp",
    deliveryPrice: 0,
    closingTime: "01:30",
    rating: 4.4,
  },
  {
    id: 9,
    name: "Burger King - Interlagos",
    slug: "burger-king-interlagos",
    image: "/images/stores/burguer-king.png",
    deliveryPrice: 6.0,
    closingTime: "20:00",
    rating: 4.7,
  },
];

export const mockStoreDetails: Record<string, StoreDetails> = {
  "matsuri-concept": {
    id: 1,
    name: "Matsuri Concept",
    slug: "matsuri-concept",
    image: "/images/stores/matsuri.png",
    deliveryFee: 0,
    deliveryTime: "30-40 min",
    distanceFromUser: "5.2km",
    closingTime: "23:00",
    rating: 4.5,
    isOpen: true,
    promotion: {
      type: "free_delivery",
      description: "entrega grátis acima de R$ 35,00",
      minOrderValue: 35.0,
    },
    minimumOrder: 15.0,
    menu: [
      {
        id: 1,
        title: "Niguiris",
        description: "arroz temperado coberto com fatias de peixe fresco",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Niguiri de Salmão",
            description: "Fatia de salmão fresco sobre arroz temperado",
            price: 8.5,
            originalPrice: 12.0,
            image: "/images/dishes/niguiri-salmao.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 2,
            name: "Niguiri de Atum",
            description: "Fatia de atum fresco sobre arroz temperado",
            price: 9.0,
            originalPrice: 13.0,
            image: "/images/dishes/niguiri-atum.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 3,
            name: "Niguiri de Camarão",
            description: "Camarão cozido sobre arroz temperado",
            price: 7.5,
            originalPrice: 10.0,
            image: "/images/dishes/niguiri-camarao.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "Ceviches",
        description:
          "um prato super refrescante de peixe fatiado e marinado com limão",
        hasOffer: false,
        dishes: [
          {
            id: 4,
            name: "Ceviche de Peixe",
            description: "Peixe fresco marinado com limão e cebola roxa",
            price: 28.0,
            image: "/images/dishes/ceviche-peixe.jpg",
            warning: {
              spicy: true,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 5,
            name: "Ceviche Misto",
            description:
              "Mix de frutos do mar marinados com limão e especiarias",
            price: 35.0,
            image: "/images/dishes/ceviche-misto.jpg",
            warning: {
              spicy: true,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Temakis",
        description: "sushi em forma de cone com salmão e cream cheese",
        hasOffer: false,
        dishes: [
          {
            id: 6,
            name: "Temaki de Salmão",
            description: "Cone de alga com salmão, cream cheese e pepino",
            price: 12.0,
            image: "/images/dishes/temaki-salmao.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 7,
            name: "Temaki Especial",
            description:
              "Cone de alga com salmão grelhado, cream cheese e cebolinha",
            price: 15.0,
            image: "/images/dishes/temaki-especial.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 8,
            name: "Refrigerante Lata",
            description: "Coca-Cola, Pepsi, Guaraná ou Fanta",
            price: 4.5,
            image: "/images/dishes/refrigerante.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 9,
            name: "Suco Natural",
            description: "Laranja, limão ou maracujá",
            price: 6.0,
            image: "/images/dishes/suco-natural.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "subway-avenida-center": {
    id: 2,
    name: "Subway - Avenida center",
    slug: "subway-avenida-center",
    image: "/images/stores/subway.png",
    deliveryFee: 6.0,
    deliveryTime: "25-35 min",
    distanceFromUser: "3.8km",
    closingTime: "22:30",
    rating: 4.7,
    isOpen: true,
    minimumOrder: 20.0,
    menu: [
      {
        id: 1,
        title: "Sanduíches 15cm",
        description: "sanduíches frescos no tamanho individual",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Frango Teriyaki",
            description: "Peito de frango grelhado com molho teriyaki",
            price: 12.9,
            originalPrice: 15.9,
            image: "/images/dishes/subway-frango-teriyaki.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 2,
            name: "Atum",
            description: "Atum com maionese e vegetais frescos",
            price: 13.9,
            originalPrice: 16.9,
            image: "/images/dishes/subway-atum.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 3,
            name: "Italian BMT",
            description: "Presunto, salame e pepperoni com queijo",
            price: 14.9,
            originalPrice: 17.9,
            image: "/images/dishes/subway-italian-bmt.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "Sanduíches 30cm",
        hasOffer: false,
        dishes: [
          {
            id: 4,
            name: "Frango Teriyaki 30cm",
            description:
              "Peito de frango grelhado com molho teriyaki - tamanho grande",
            price: 22.9,
            image: "/images/dishes/subway-frango-teriyaki-30.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 5,
            name: "Italian BMT 30cm",
            description:
              "Presunto, salame e pepperoni com queijo - tamanho grande",
            price: 26.9,
            image: "/images/dishes/subway-italian-bmt-30.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 6,
            name: "Refrigerante 500ml",
            description: "Coca-Cola, Pepsi ou Guaraná",
            price: 5.5,
            image: "/images/dishes/refrigerante-500ml.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "burger-king-colombo": {
    id: 3,
    name: "Burger King - Colombo",
    slug: "burger-king-colombo",
    image: "/images/stores/burguer-king.png",
    deliveryFee: 6.0,
    deliveryTime: "20-30 min",
    distanceFromUser: "2.1km",
    closingTime: "00:00",
    rating: 4.7,
    isOpen: true,
    promotion: {
      type: "discount",
      description: "20% off no segundo hambúrguer",
      minOrderValue: 25.0,
    },
    minimumOrder: 18.0,
    menu: [
      {
        id: 1,
        title: "Whopper",
        description: "os clássicos hambúrguers flame grilled",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Whopper",
            description:
              "Hamburger bovino grelhado com alface, tomate, cebola, picles e maionese",
            price: 18.9,
            originalPrice: 22.9,
            image: "/images/dishes/whopper.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 2,
            name: "Whopper Duplo",
            description:
              "Dois hambúrgueres bovinos grelhados com todos os acompanhamentos",
            price: 26.9,
            originalPrice: 32.9,
            image: "/images/dishes/whopper-duplo.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 3,
            name: "Whopper Jr",
            description: "Versão menor do clássico Whopper",
            price: 12.9,
            originalPrice: 15.9,
            image: "/images/dishes/whopper-jr.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "Chicken",
        description: "hambúrgueres de frango crocante",
        hasOffer: false,
        dishes: [
          {
            id: 4,
            name: "Chicken Crispy",
            description: "Frango empanado crocante com alface e maionese",
            price: 16.9,
            image: "/images/dishes/chicken-crispy.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 5,
            name: "BK Chicken",
            description: "Frango grelhado com alface, tomate e maionese",
            price: 14.9,
            image: "/images/dishes/bk-chicken.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Acompanhamentos",
        hasOffer: false,
        dishes: [
          {
            id: 6,
            name: "Batata Frita Média",
            description: "Porção média de batatas fritas crocantes",
            price: 8.9,
            image: "/images/dishes/batata-frita.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 7,
            name: "Onion Rings",
            description: "Anéis de cebola empanados e fritos",
            price: 9.9,
            image: "/images/dishes/onion-rings.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 8,
            name: "Refrigerante 500ml",
            description: "Coca-Cola, Fanta ou Sprite",
            price: 6.9,
            image: "/images/dishes/refrigerante-500ml.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "mcdonalds-novo-centro": {
    id: 4,
    name: "McDonald's - Novo Centro",
    slug: "mcdonalds-novo-centro",
    image: "/images/stores/mcdonalds.png",
    deliveryFee: 0,
    deliveryTime: "15-25 min",
    distanceFromUser: "1.5km",
    closingTime: "23:30",
    rating: 4.7,
    isOpen: true,
    promotion: {
      type: "free_delivery",
      description: "entrega grátis sem valor mínimo",
      minOrderValue: 0,
    },
    minimumOrder: 15.0,
    menu: [
      {
        id: 1,
        title: "Big Mac",
        description: "o clássico hambúrguer com dois hambúrgueres",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Big Mac",
            description:
              "Dois hambúrgueres, alface, queijo, molho especial, cebola e picles",
            price: 19.9,
            originalPrice: 24.9,
            image: "/images/dishes/big-mac.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 2,
            name: "Quarter Pounder",
            description: "Hambúrguer de 1/4 de libra com queijo",
            price: 22.9,
            originalPrice: 27.9,
            image: "/images/dishes/quarter-pounder.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "McNuggets",
        description: "pedaços de frango empanado crocante",
        hasOffer: false,
        dishes: [
          {
            id: 3,
            name: "McNuggets 10 unidades",
            description: "10 pedaços de frango empanado com molhos",
            price: 16.9,
            image: "/images/dishes/mcnuggets-10.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 4,
            name: "McNuggets 20 unidades",
            description: "20 pedaços de frango empanado com molhos",
            price: 28.9,
            image: "/images/dishes/mcnuggets-20.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "McFritas",
        hasOffer: false,
        dishes: [
          {
            id: 5,
            name: "Batata Frita Pequena",
            description: "Porção pequena das famosas batatas do McDonald's",
            price: 5.9,
            image: "/images/dishes/mcfritas-pequena.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 6,
            name: "Batata Frita Média",
            description: "Porção média das famosas batatas do McDonald's",
            price: 7.9,
            image: "/images/dishes/mcfritas-media.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 7,
            name: "Coca-Cola 500ml",
            description: "Refrigerante Coca-Cola gelado",
            price: 5.9,
            image: "/images/dishes/coca-cola-500ml.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "pizza-hut-centro": {
    id: 5,
    name: "Pizza Hut - Centro",
    slug: "pizza-hut-centro",
    image: "/images/stores/pizza-hut.webp",
    deliveryFee: 8.0,
    deliveryTime: "35-45 min",
    distanceFromUser: "4.2km",
    closingTime: "01:00",
    rating: 4.5,
    isOpen: true,
    promotion: {
      type: "discount",
      description: "30% off na segunda pizza",
      minOrderValue: 40.0,
    },
    minimumOrder: 25.0,
    menu: [
      {
        id: 1,
        title: "Pizzas Tradicionais",
        description: "nossas pizzas clássicas com massa tradicional",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Pizza Marguerita",
            description: "Molho de tomate, mussarela, tomate e manjericão",
            price: 32.9,
            originalPrice: 39.9,
            image: "/images/dishes/pizza-marguerita.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 2,
            name: "Pizza Pepperoni",
            description: "Molho de tomate, mussarela e pepperoni",
            price: 36.9,
            originalPrice: 42.9,
            image: "/images/dishes/pizza-pepperoni.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 3,
            name: "Pizza Quatro Queijos",
            description: "Mussarela, parmesão, gorgonzola e catupiry",
            price: 38.9,
            originalPrice: 44.9,
            image: "/images/dishes/pizza-quatro-queijos.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "Pizzas Especiais",
        description: "criações especiais da casa",
        hasOffer: false,
        dishes: [
          {
            id: 4,
            name: "Pizza Supreme",
            description:
              "Pepperoni, linguiça, pimentão, cebola, azeitona e cogumelos",
            price: 45.9,
            image: "/images/dishes/pizza-supreme.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 5,
            name: "Pizza Frango Catupiry",
            description: "Frango desfiado, catupiry, milho e azeitona",
            price: 42.9,
            image: "/images/dishes/pizza-frango-catupiry.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Acompanhamentos",
        hasOffer: false,
        dishes: [
          {
            id: 6,
            name: "Pão de Alho",
            description: "Pão italiano com alho e ervas",
            price: 12.9,
            image: "/images/dishes/pao-de-alho.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 7,
            name: "Refrigerante 2L",
            description: "Coca-Cola, Guaraná ou Fanta 2 litros",
            price: 9.9,
            image: "/images/dishes/refrigerante-2l.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "kfc-shopping": {
    id: 6,
    name: "KFC - Shopping",
    slug: "kfc-shopping",
    image: "/images/stores/kfc.webp",
    deliveryFee: 5.0,
    deliveryTime: "25-35 min",
    distanceFromUser: "3.1km",
    closingTime: "22:00",
    rating: 4.6,
    isOpen: true,
    minimumOrder: 20.0,
    menu: [
      {
        id: 1,
        title: "Baldes de Frango",
        description:
          "frango crocante com a receita secreta de 11 ervas e especiarias",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Balde 8 Pedaços",
            description: "8 pedaços de frango crocante com 2 acompanhamentos",
            price: 42.9,
            originalPrice: 52.9,
            image: "/images/dishes/kfc-balde-8.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 2,
            name: "Balde 12 Pedaços",
            description: "12 pedaços de frango crocante com 3 acompanhamentos",
            price: 58.9,
            originalPrice: 69.9,
            image: "/images/dishes/kfc-balde-12.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "Hot Wings",
        description: "asinhas de frango picantes",
        hasOffer: false,
        dishes: [
          {
            id: 3,
            name: "Hot Wings 6 unidades",
            description: "6 asinhas de frango apimentadas",
            price: 18.9,
            image: "/images/dishes/hot-wings-6.jpg",
            warning: {
              spicy: true,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 4,
            name: "Hot Wings 12 unidades",
            description: "12 asinhas de frango apimentadas",
            price: 32.9,
            image: "/images/dishes/hot-wings-12.jpg",
            warning: {
              spicy: true,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Acompanhamentos",
        hasOffer: false,
        dishes: [
          {
            id: 5,
            name: "Batata Rústica",
            description: "Batatas com casca temperadas",
            price: 8.9,
            image: "/images/dishes/batata-rustica.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 6,
            name: "Salada de Repolho",
            description: "Salada tradicional de repolho",
            price: 6.9,
            image: "/images/dishes/salada-repolho.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 7,
            name: "Refrigerante 500ml",
            description: "Pepsi, Guaraná ou H2OH",
            price: 5.9,
            image: "/images/dishes/refrigerante-500ml.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "outback-steakhouse": {
    id: 7,
    name: "Outback Steakhouse",
    slug: "outback-steakhouse",
    image: "/images/stores/outback.webp",
    deliveryFee: 12.0,
    deliveryTime: "40-55 min",
    distanceFromUser: "6.8km",
    closingTime: "23:45",
    rating: 4.8,
    isOpen: true,
    promotion: {
      type: "discount",
      description: "15% off em carnes acima de R$ 80",
      minOrderValue: 80.0,
    },
    minimumOrder: 35.0,
    menu: [
      {
        id: 1,
        title: "Steaks",
        description: "carnes nobres grelhadas no ponto",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Ribeye 400g",
            description: "Contra-filé maturado com 400g, grelhado no ponto",
            price: 89.9,
            originalPrice: 105.9,
            image: "/images/dishes/ribeye.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
          {
            id: 2,
            name: "New York Strip",
            description: "Contra-filé americano de 350g",
            price: 78.9,
            originalPrice: 92.9,
            image: "/images/dishes/new-york-strip.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "Appetizers",
        description: "entradas para compartilhar",
        hasOffer: false,
        dishes: [
          {
            id: 3,
            name: "Bloomin' Onion",
            description: "Cebola gigante empanada e frita com molho especial",
            price: 28.9,
            image: "/images/dishes/bloomin-onion.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 4,
            name: "Chicken Wings",
            description: "Asinhas de frango com molho barbecue",
            price: 32.9,
            image: "/images/dishes/outback-wings.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Acompanhamentos",
        hasOffer: false,
        dishes: [
          {
            id: 5,
            name: "Batata Assada",
            description: "Batata assada com manteiga e cebolinha",
            price: 14.9,
            image: "/images/dishes/batata-assada.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 6,
            name: "Limonada Outback",
            description: "Limonada especial da casa",
            price: 12.9,
            image: "/images/dishes/limonada-outback.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "dominos-pizza": {
    id: 8,
    name: "Domino's Pizza",
    slug: "dominos-pizza",
    image: "/images/stores/dominos.webp",
    deliveryFee: 0,
    deliveryTime: "30-40 min",
    distanceFromUser: "2.8km",
    closingTime: "01:30",
    rating: 4.4,
    isOpen: true,
    promotion: {
      type: "free_delivery",
      description: "entrega grátis sem valor mínimo",
      minOrderValue: 0,
    },
    minimumOrder: 20.0,
    menu: [
      {
        id: 1,
        title: "Pizzas Tradicionais",
        description: "pizzas clássicas com massa hand tossed",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Pizza Mussarela",
            description: "Molho de tomate e mussarela especial",
            price: 28.9,
            originalPrice: 34.9,
            image: "/images/dishes/dominos-mussarela.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 2,
            name: "Pizza Pepperoni",
            description: "Molho de tomate, mussarela e pepperoni importado",
            price: 32.9,
            originalPrice: 38.9,
            image: "/images/dishes/dominos-pepperoni.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "Pizzas Especiais",
        description: "criações exclusivas Domino's",
        hasOffer: false,
        dishes: [
          {
            id: 3,
            name: "Pizza Americana",
            description: "Pepperoni, calabresa, pimentão e cebola",
            price: 39.9,
            image: "/images/dishes/dominos-americana.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 4,
            name: "Pizza Brasileira",
            description: "Calabresa, cebola, pimentão, azeitona e orégano",
            price: 36.9,
            image: "/images/dishes/dominos-brasileira.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Acompanhamentos",
        hasOffer: false,
        dishes: [
          {
            id: 5,
            name: "Pão de Alho Recheado",
            description: "Pão de alho com queijo mussarela",
            price: 15.9,
            image: "/images/dishes/pao-alho-recheado.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 6,
            name: "Refrigerante 2L",
            description: "Coca-Cola, Fanta ou Sprite 2 litros",
            price: 8.9,
            image: "/images/dishes/refrigerante-2l.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },

  "burger-king-interlagos": {
    id: 9,
    name: "Burger King - Interlagos",
    slug: "burger-king-interlagos",
    image: "/images/stores/burguer-king.png",
    deliveryFee: 6.0,
    deliveryTime: "25-35 min",
    distanceFromUser: "7.2km",
    closingTime: "20:00",
    rating: 4.7,
    isOpen: true,
    promotion: {
      type: "discount",
      description: "combo especial 2 por R$ 25",
      minOrderValue: 25.0,
    },
    minimumOrder: 18.0,
    menu: [
      {
        id: 1,
        title: "Whopper",
        description: "os clássicos hambúrguers flame grilled",
        hasOffer: true,
        dishes: [
          {
            id: 1,
            name: "Whopper",
            description:
              "Hamburger bovino grelhado com alface, tomate, cebola, picles e maionese",
            price: 18.9,
            originalPrice: 22.9,
            image: "/images/dishes/whopper.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 2,
            name: "Whopper Bacon",
            description: "Whopper tradicional com bacon crocante",
            price: 21.9,
            originalPrice: 26.9,
            image: "/images/dishes/whopper-bacon.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 2,
        title: "BK Especiais",
        description: "hamburguers exclusivos da casa",
        hasOffer: false,
        dishes: [
          {
            id: 3,
            name: "BK Tasty",
            description: "Hamburger bovino com queijo cheddar e molho tasty",
            price: 16.9,
            image: "/images/dishes/bk-tasty.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
          {
            id: 4,
            name: "Big King",
            description:
              "Dois hambúrgueres, queijo, alface, cebola e molho especial",
            price: 19.9,
            image: "/images/dishes/big-king.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: false,
              glutenFree: false,
            },
            available: true,
          },
        ],
      },
      {
        id: 3,
        title: "Acompanhamentos",
        hasOffer: false,
        dishes: [
          {
            id: 5,
            name: "Batata Frita Grande",
            description: "Porção grande de batatas fritas crocantes",
            price: 10.9,
            image: "/images/dishes/batata-frita-grande.jpg",
            warning: {
              spicy: false,
              vegan: true,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
      {
        id: 4,
        title: "Bebidas",
        hasOffer: false,
        dishes: [
          {
            id: 6,
            name: "Milkshake",
            description: "Milkshake cremoso de baunilha, chocolate ou morango",
            price: 12.9,
            image: "/images/dishes/milkshake.jpg",
            warning: {
              spicy: false,
              vegan: false,
              vegetarian: true,
              glutenFree: true,
            },
            available: true,
          },
        ],
      },
    ],
  },
};
